#!/bin/sh

set -e

case "$1" in
    remove|purge|upgrade    )
        [ -d /run/systemd/system ] && {
        systemctl --system daemon-reload >/dev/null || true ; }


        [ -x "/usr/bin/deb-systemd-helper" ] && {
        deb-systemd-helper stop 'grub-btrfsd.service' >/dev/null || true ; }

        [ -x "/usr/bin/deb-systemd-helper" ] && {
        deb-systemd-helper purge 'grub-btrfsd.service' >/dev/null || true
        deb-systemd-helper unmask 'grub-btrfsd.service' >/dev/null || true ; }
    ;;
    failed-upgrade  ) ;;
    *               ) echo "Unsupported option $1" >&2 ; exit 1 ;;
esac

