#!/bin/bash

set -eo pipefail

case "${1}" in
    configure|upgrade|reinstall )

        # Check if Timeshift is installed and if so then modify the systemd service
        if command -v timeshift &> /dev/null ; then
            sed -i 's|^//.snapshots|--timeshift-old --timeshift-new|g' \
                /usr/lib/systemd/system/grub-btrfsd.service
        fi

        if systemctl is-active --quiet grub-btrfsd.service ; then
            systemctl daemon-reload ; systemctl restart grub-btrfsd.service
        else
            systemctl enable --now grub-btrfsd.service
        fi
    ;;

    *)
        echo "postinst called with unknown argument: $1" >&2
        exit 1
    ;;
esac
