#!/bin/env bash

set -e

# shellcheck disable=SC2046
if test -d "../../mls" ; then
    rm -vf ../../mls/pool/main/g/"${PACKAGE}"/*.deb
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" \
		"../../mls/pool/main/g/${PACKAGE}/${PACKAGE}_${VERSION}_${ARCH}.deb"
else
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" "${PACKAGE}_${VERSION}_${ARCH}.deb"
fi